### ISSUE TITLE
Support docker registry authentication when pulling chaincode builder images and chaincode runtime images

### ISSUE THREAD

**Issue by Alex-duzhichao** [hyperledger/fabric#3014]
When deploying fabric in enterprise's intranet (without the ability to access internet),  users maybe upload chaincode builder images and chaincode runtime images to a private docker registry which requires authentication when pulling images.
I think fabric can support this scenario by adding configuration in `chaincode` section of core.yaml, such as:
```yaml
chaincode:
    registry:
        authentication:
              user: ****
              password: ****
```

and then uses this configuration for authentication when invoking docker's api .
