### ISSUE TITLE
Clarify: can external chaincode be replicated?

### ISSUE THREAD

**Issue by jkopczyn** [hyperledger/fabric#3319]
Looking at [Configuring a peer to process external chaincode](https://hyperledger-fabric.readthedocs.io/en/release-2.2/cc_service.html#modify-the-peer-core-yaml-to-include-the-externalbuilder) and [Writing chaincode to run as an external service](https://hyperledger-fabric.readthedocs.io/en/release-2.2/cc_service.html#go), it looks like it should be possible for a chaincode to be run on multiple machines and for a peer to connect to those multiple instances (with some form of load balancing), by making multiple calls to `shim.ChaincodeServer` and defining multiple external builders with

```
externalBuilders:
     - name: myexternal1
       path: <fully qualified path to #1 on the peer's env>  
     - name: myexternal2
       path: <fully qualified path to #2 on the peer's env>  
```

And so on. Is this in fact possible?
