### ISSUE TITLE
v2.5.0 orderer with pkcs11 cannot start

### ISSUE THREAD

**Issue by bh4rtp** [hyperledger/fabric#4146]
### Description

Orderer cannot start, but peer can. v2.4.9 orderer also run ok.

Error log in orderer:

2023-04-05 10:27:43.592 CST 0003 PANI [orderer.common.server] loadLocalMSP -> Failed to setup local msp with config: KeyMaterial not found in SigningIdentityInfo
panic: Failed to setup local msp with config: KeyMaterial not found in SigningIdentityInfo

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001a49c0, {0x0, 0x0, 0x0})
        /vendor/go.uber.org/zap/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc000146148, 0x4, {0x10e8337?, 0xc0000db190?}, {0xc0000db190?, 0x0?, 0x1000000000000?}, {0x0, 0x0, 0x0})
        /vendor/go.uber.org/zap/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
        /common/flogging/zap.go:74
github.com/hyperledger/fabric/orderer/common/server.loadLocalMSP(0xf39100?)
        /orderer/common/server/main.go:778 +0x2a8
github.com/hyperledger/fabric/orderer/common/server.Main()
        /orderer/common/server/main.go:93 +0x1ce
main.main()
        /cmd/orderer/main.go:15 +0x17

### Steps to reproduce

Build fabric release 2.5.0 with GO_TAGS=PKCS11 and softhsm.

**Comment by denyeart** [comment]
GO_TAGS=PKCS11 and softhsm appears to be working in fabric-test on v2.5.

@davidkel Any ideas?

**Comment by davidkel** [comment]
@denyeart As you say it's tested via fabric-test (although technically fabric-test doesn't have the peer/orderer use softhsm directly as it uses a proxy but given it's common code and it's working for peers this isn't a likely consideration) so don't know what the issue could be. Maybe check the orderer logs which show the configuration it's working with, plus maybe enable debug on the appropriate component (I've no idea what component it would be though) to get debug logging of the bccsp and also show the logging specifically within the pkcs11 code to show that it's going via pkcs11. That error could suggest that it's falling back to SW for example.

**Comment by bh4rtp** [comment]
@davidkel You are right, orderer started with SW BCCSP. While BCCSP is configured with PKCS11 in orderer.yaml like this:
```
BCCSP:
        Default: PKCS11
        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:
        PKCS11:
            Library: /usr/lib/softhsm/libsofthsm2.so
            Label: fabric
            Pin: 87654321
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:

```
