### ISSUE TITLE
SHA3 not actually work in orderer and peer

### ISSUE THREAD

**Issue by bh4rtp** [hyperledger/fabric#4179]
### Description

Configure BCCSP with SW SHA3 384 in `orderer.yaml` and `core.yaml`, orderer and peer can start ok.
But when using node sdk with SHA3 384, it does not work. 
```
2023-04-21T01:49:37.431Z - error: [DiscoveryResultsProcessor]: parseDiscoveryResults[democh] - Channel:democh received discovery error:access denied
Error in transaction: Error: DiscoveryService: democh error: access denied
```
I check the `peer channel fetch config` output which shows actually SHA2 256.
```
"crypto_config": {
                      "identity_identifier_hash_function": "SHA256",
                      "signature_hash_family": "SHA2"
                    },
```

### Steps to reproduce

1) BCCSP configuration for `orderer.yaml` and `core.yaml`:
```
BCCSP:
        Default: SW
        SW:
            Hash: SHA3
            Security: 384
            FileKeyStore:
                KeyStore:
```

2) start fabric network.
3) start node app and register identity.
