### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by pedromnchunks35** [hyperledger/fabric#4287]
### Description

Hello, i am trying to deploy a orderer using the image provided by the install.sh script. I am following the Fabric CA Operations guide "https://hyperledger-fabric-ca.readthedocs.io/en/latest/operations_guide.html#setup-orderer". Unfortunelly, because i firstly did a guide to setup all the fabric CA's, i created a CA chain because it follows the good practises. Since i did that, i needed to adapt the tutorial to my needs and by doing that i went into a error that stackoverflow says is a error in the certificate i just generated. The error is as follow: 

./scripts.sh 
2023-06-15 08:48:06.110 UTC 0001 WARN [localconfig] completeInitialization -> General.GenesisFile should be replaced by General.BootstrapFile
2023-06-15 08:48:06.110 UTC 0002 INFO [localconfig] completeInitialization -> Kafka.Version unset, setting to 0.10.2.0
2023-06-15 08:48:06.110 UTC 0003 INFO [orderer.common.server] prettyPrintStruct -> Orderer config values:
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/tmp/hyperledger/orderer/orderer/tls-msp/keystore/key.pem"
	General.TLS.Certificate = "/tmp/hyperledger/orderer/orderer/tls-msp/signcerts/cert.pem"
	General.TLS.RootCAs = [/tmp/hyperledger/orderer/orderer/tls-msp/tlscacerts/tls-192-168-1-78-7777.pem]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.TLS.TLSHandshakeTimeShift = 0s
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 100
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = "file"
	General.GenesisFile = "/tmp/hyperledger/orderer/genesis.block"
	General.BootstrapMethod = "file"
	General.BootstrapFile = "/tmp/hyperledger/orderer/genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/tmp/hyperledger/orderer/orderer/msp"
	General.LocalMSPID = "ordererMSP"
	General.BCCSP.Default = "SW"
	General.BCCSP.SW.Security = 256
	General.BCCSP.SW.Hash = "SHA2"
	General.BCCSP.SW.FileKeystore.KeyStorePath = ""
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	General.MaxRecvMsgSize = 104857600
	General.MaxSendMsgSize = 104857600
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = ""
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.TLS.TLSHandshakeTimeShift = 0s
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = "data/logs"
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "127.0.0.1:8443"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = ""
	Operations.TLS.Certificate = ""
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = []
	Operations.TLS.TLSHandshakeTimeShift = 0s
	Metrics.Provider = "disabled"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
	ChannelParticipation.Enabled = false
	ChannelParticipation.MaxRequestBodySize = 1048576
	Admin.ListenAddress = "127.0.0.1:9443"
	Admin.TLS.Enabled = false
	Admin.TLS.PrivateKey = ""
	Admin.TLS.Certificate = ""
	Admin.TLS.RootCAs = []
	Admin.TLS.ClientAuthRequired = true
	Admin.TLS.ClientRootCAs = []
	Admin.TLS.TLSHandshakeTimeShift = 0s
2023-06-15 08:48:06.113 UTC 0004 INFO [orderer.common.server] initializeServerConfig -> Starting orderer with TLS enabled
2023-06-15 08:48:06.123 UTC 0005 INFO [blkstorage] NewProvider -> Creating new file ledger directory at /var/hyperledger/production/orderer/chains
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/hyperledger/fabric/msp.(*bccspmsp).sanitizeCert(0xc0000be897?, 0xc0001aeb00)
	/msp/mspimpl.go:924 +0x245
github.com/hyperledger/fabric/msp.newIdentity(0xc000456d20?, {0x121e0d8?, 0xc000125cf0}, 0xc0003ce000)
	/msp/identities.go:61 +0x105
github.com/hyperledger/fabric/msp.(*bccspmsp).getIdentityFromConf(0xc0003ce000, {0xc000144900?, 0x40f?, 0x480?})
	/msp/mspimpl.go:200 +0x9e
github.com/hyperledger/fabric/msp.(*bccspmsp).setupCAs(0xc0003ce000, 0xc0002d03c0)
	/msp/mspimplsetup.go:135 +0x41f
github.com/hyperledger/fabric/msp.(*bccspmsp).preSetupV142(0xc0003ce000, 0x92d4e2?)
	/msp/mspimplsetup.go:570 +0x3f
github.com/hyperledger/fabric/msp.(*bccspmsp).setupV142(0xed8320?, 0xc0002d0301?)
	/msp/mspimplsetup.go:646 +0x25
github.com/hyperledger/fabric/msp.(*bccspmsp).Setup(0xc0003ce000, 0xc0003c3a40)
	/msp/mspimpl.go:267 +0x146
github.com/hyperledger/fabric/msp/cache.(*cachedMSP).Setup(0xc0002186c0, 0xc0003ce000?)
	/msp/cache/cache.go:87 +0x3c
github.com/hyperledger/fabric/common/channelconfig.(*MSPConfigHandler).ProposeMSP(0xc000041400, 0xc0003c3a40)
	/common/channelconfig/msp.go:75 +0x2b6
github.com/hyperledger/fabric/common/channelconfig.(*OrganizationConfig).validateMSP(0xc0003c3a80)
	/common/channelconfig/organization.go:85 +0xa7
github.com/hyperledger/fabric/common/channelconfig.(*OrganizationConfig).Validate(...)
	/common/channelconfig/organization.go:78
github.com/hyperledger/fabric/common/channelconfig.(*OrdererOrgConfig).Validate(...)
	/common/channelconfig/orderer.go:119
github.com/hyperledger/fabric/common/channelconfig.NewOrdererOrgConfig({0xc000284410, 0x7}, 0xc000024460, 0xc000041400, {0x121c0e8?, 0xc000377cb0?})
	/common/channelconfig/orderer.go:111 +0x216
github.com/hyperledger/fabric/common/channelconfig.NewOrdererConfig(0xc000024410, 0x121c0e8?, {0x121c0e8, 0xc000377cb0})
	/common/channelconfig/orderer.go:139 +0x1cc
github.com/hyperledger/fabric/common/channelconfig.NewChannelConfig(0xc0000240a0, {0x1222e00?, 0xc000456d20})
	/common/channelconfig/channel.go:103 +0x2d4
github.com/hyperledger/fabric/common/channelconfig.NewBundle({0xc000284890, 0xa}, 0xc0003b39b0, {0x1222e00, 0xc000456d20})
	/common/channelconfig/bundle.go:187 +0x8a
github.com/hyperledger/fabric/common/channelconfig.NewBundleFromEnvelope(0xc0000a4800?, {0x1222e00, 0xc000456d20})
	/common/channelconfig/bundle.go:178 +0xe5
github.com/hyperledger/fabric/orderer/common/onboarding.ValidateBootstrapBlock(0xc0003c2440, {0x1222e00, 0xc000456d20})
	/orderer/common/onboarding/onboarding.go:427 +0xbd
github.com/hyperledger/fabric/orderer/common/server.Main()
	/orderer/common/server/main.go:129 +0x745
main.main()
	/cmd/orderer/main.go:15 +0x17

I came here to this repository and i'm founding that the line in the error, actually is acusing a error in my certificate chain which i think it may be an error in the local msp of the orderer. By acknowledging that, i started to dig into what i have and i don't understand whats wrong. The local msp is composed as follow:

msp
    ├── admincerts
                                   └──   org1-admin-cert.pem
    ├── cacerts
                            └──  192-168-1-XX-XXXX.pem
    ├── intermediatecerts
                                               └── 192-168-1-XX-XXXX.pem
    ├── IssuerPublicKey
    ├── IssuerRevocationPublicKey
    ├── keystore
                              └── key.pem
    ├── signcerts
                               └── cert.pem
    └── user

These are the certificates:
admincerts/org1-admin-cert.pem
![Screenshot_2023-06-17_12-30-59](https://github.com/hyperledger/fabric/assets/48800536/aae6493b-c885-484f-9427-a6392ff05537)

cacerts/192-168-1-XX-XXXX.pem
![cacerts](https://github.com/hyperledger/fabric/assets/48800536/629f14ab-59b1-4a0d-ba50-04b5d824e9a2)

intermediatecerts/192-168-1-XX-XXXX.pem
![inter](https://github.com/hyperledger/fabric/assets/48800536/55c1f6ed-eef4-4b39-abd3-4e424a79c769)

signcerts/cert.pem
![sign](https://github.com/hyperledger/fabric/assets/48800536/82662d19-ae91-4d2c-bb23-d74290b02b2b)

Idk, if it is relevant but these are the configurations for the configtx.yaml:
```
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: ./org1/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"
        # Anchor peers
        AnchorPeers:
            - Host: 
              Port: 
            - Host: 
              Port:
            

################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
    Channel: &ChannelCapabilities
        # V2_0 capability ensures that orderers and peers behave according
        # to v2.0 channel capabilities. Orderers and peers from
        # prior releases would behave in an incompatible way, and are therefore
        # not able to participate in channels at v2.0 capability.
        # Prior to enabling V2.0 channel capabilities, ensure that all
        # orderers and peers on a channel are at v2.0.0 or later.
        V2_0: true
        

    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
    Orderer: &OrdererCapabilities
        # V2_0 orderer capability ensures that orderers behave according
        # to v2.0 orderer capabilities. Orderers from
        # prior releases would behave in an incompatible way, and are therefore
        # not able to participate in channels at v2.0 orderer capability.
        # Prior to enabling V2.0 orderer capabilities, ensure that all
        # orderers on channel are at v2.0.0 or later.
        V2_0: true

    # Application capabilities apply only to the peer network, and may be safely
    # used with prior release orderers.
    # Set the value of the capability to true to require it.
    Application: &ApplicationCapabilities
        # V2.5 for Application enables the new non-backwards compatible
        # features of fabric v2.5, namely the ability to purge private data.
        # Prior to enabling V2.5 application capabilities, ensure that all
        # peers on a channel are at v2.5.0 or later.
        V2_5: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: etcdraft
    # Addresses used to be the list of orderer addresses that clients and peers
    # could connect to.  However, this does not allow clients to associate orderer
    # addresses and orderer organizations which can be useful for things such
    # as TLS validation.  The preferred way to specify orderer addresses is now
    # to include the OrdererEndpoints item in your org definition
    Addresses:
        - 192.168.1.101:7050

    EtcdRaft:
        Consenters:
        - Host: 
          Port: 
          ClientTLSCert: ./orderer/tls-msp/signcerts/cert.pem
          ServerTLSCert: ./orderer/ca-client/tls-cas/tls-root-ca.pem

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Org1
            Capabilities: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1

    Channel:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1

```

And these is the script that i am using to deploy the container (yes i am not using docker compose)

```
docker run \
  --name orderer \
  -p 7050:7050 \
  -e ORDERER_HOME=/tmp/hyperledger/orderer \
  -e ORDERER_HOST=127.0.0.1:XXXX \
  -e ORDERER_GENERAL_LISTENADDRESS=0.0.0.0\
  -e ORDERER_GENERAL_GENESISMETHOD=file \
  -e ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/orderer/genesis.block \
  -e ORDERER_GENERAL_LOCALMSPID=ordererMSP \
  -e ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/orderer/orderer/msp \
  -e ORDERER_GENERAL_TLS_ENABLED=true \
  -e ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/orderer/orderer/tls-msp/signcerts/cert.pem \
  -e ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/orderer/orderer/tls-msp/keystore/key.pem \
  -e ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/orderer/orderer/tls-msp/tlscacerts/tls-192-168-1-XX-XXXX.pem] \
  -e ORDERER_GENERAL_LOGLEVEL=debug \
  -e ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs \
  -v /root/go-workspace/src/github.com/pedromnchunks/deploy-orderer/:/tmp/hyperledger/orderer/ \
  hyperledger/fabric-orderer
```

Could you help me?
