### ISSUE TITLE
Hyperledger Fabric Connection issues with Docker Swarm on GCP instances

### ISSUE THREAD

**Issue by crissiaccubits** [hyperledger/fabric#4288]
![Screenshot from 2023-06-19 13-48-24](https://github.com/hyperledger/fabric/assets/41966089/974f945e-f6d7-4980-898d-5df1d9e91fa8)

I have created a Hyperledger Fabric (version 2.2) network consisting of four nodes, with two nodes hosted on AWS instances and the other two on GCP instances. I have connected these nodes using a Docker Swarm network with public IP addresses.

All the Docker services for the nodes were up and able to connect to each other. However, when I tried to install Chaincode on the GCP peer instance, I encountered the error message as follows:
`Error getting endorser client for install: context deadline exceeded.`
`![Screenshot from 2023-06-19 13-48-24](https://github.com/hyperledger/fabric/assets/41966089/1a0624cc-829d-4453-8394-fbb0a6f807d3)`
Additionally, the GCP peer logs indicated a TLS handshake failure.

Furthermore, when I attempted to add a new peer node on the GCP instance, I received the error message as `Client TLS handshake failed after 10.669562ms with error: x509: certificate signed by unknown authority( This error may be related to "x509: ECDSA verification failure) during the attempt install the chaincode.`

I suspect that these errors are caused by connection issues with Docker on GCP instances since I am not experiencing any issues on the AWS instances.

Is there anything specific that needs to be configured to establish connectivity between GCP and AWS instances in this context?

I am adding docker compose file for an org for the reference:

```
 ca_Org1: 
  image: hyperledger/fabric-ca:1.5.3 
  environment: 
   - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server 
   - FABRIC_CA_SERVER_CA_NAME=ca_Org1
   - FABRIC_CA_SERVER_TLS_ENABLED=true 
   - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.peer1_org_io-cert.pem 
   - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d51088bc60b8dd029c83716eaf6f8b3d1a87ab35b180a2268f53189ced4227ff_sk 
   - GODEBUG=netdns=go 
  ports: 
   - 7054:7054 
  command: sh -c "fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org_io-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d51088bc60b8dd029c83716eaf6f8b3d1a87ab35b180a2268f53189ced4227ff_sk -b admina:adminpw -d" 
  volumes: 
   - /opt/dlt/org/Org1/crypto-config/peerOrganizations/org_io/ca/:/etc/hyperledger/fabric-ca-server-config 
  container_name: ca_Org1
  networks: 
  - dev 
  deploy: 
    replicas: 1 
    placement: 
      constraints: 
        - node.id == tuf7wb05mkl4ncw0spn8z2lss 
  restart: always 
  logging: 
    driver: "json-file" 
    options: 
      max-file: 5 
      max-size: 10m 
  depends_on: 
    - ord5_standardc_io 
    - ord4_standardc_io 
    - ord3_standardc_io 
    - ord2_standardc_io 
    - ord1_standardc_io 
    #ORDERER_GROUP 
 
 couchdb_peer1_org_io: 
  container_name: couchdb_peer1_org_io
  ports: 
   - 7984:5984 
  image: hyperledger/fabric-couchdb:0.4.18 
  environment: 
   - COUCHDB_USER=admin 
   - COUCHDB_PASSWORD=P@ss123 
  networks: 
   - dev 
  deploy: 
    replicas: 1 
    placement: 
      constraints: 
        - node.id == tuf7wb05mkl4ncw0spn8z2lss 
  volumes: 
    - /opt/dlt/org/Org1/hyp-data/couchdb/:/opt/couchdb/data 
  logging: 
    driver: "json-file" 
    options: 
      max-file: 5 
      max-size: 10m 
  restart: always 
  depends_on: 
    - ord5_standardc_io 
    - ord4_standardc_io 
    - ord3_standardc_io 
    - ord2_standardc_io 
    - ord1_standardc_io 
    #ORDERER_GROUP 
 
peer1_org_io: 
  container_name: peer1_org_io
  image: hyperledger/fabric-peer:2.2.7 
  environment: 
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock 
    - CORE_PEER_ID=peer1_org_io
    - CORE_PEER_LOCALMSPID=Org1MSP 
    - CORE_PEER_ADDRESS=peer1_org_io:7051 
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer1_org_io:5984 
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1_org_io:7051 
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1_org_io:7051 
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=swarmProdNew_dev 
    - FABRIC_LOGGING_SPEC=ERROR 
    - CORE_CHAINCODE_LOGGING_LEVEL=ERROR 
    - CORE_PEER_GOSSIP_USELEADERELECTION=true 
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp 
    - CORE_PEER_GOSSIP_ORGLEADER=false 
    - CORE_PEER_PROFILE_ENABLED=true 
    - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:2.2.7 
    #TLS Settings 
    - CORE_PEER_TLS_ENABLED=true 
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt 
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key 
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt 
    - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false 
    - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/peer/tls/server.crt 
    - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/peer/tls/server.key 
    - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/peer/tls/ca.crt 
    #Couch DB config 
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB 
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin 
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=P@ss123 
    - GODEBUG=netdns=go 
  volumes: 
    - /var/run/:/host/var/run/ 
    - /opt/dlt/org/Org1/config/:/etc/hyperledger/configtx 
    - /opt/dlt/org/Org1/crypto-config/peerOrganizations/org_io/peers/peer1_org_io:/etc/hyperledger/peer 
    - /opt/dlt/org/Org1/crypto-config/peerOrganizations/org_io/users:/etc/hyperledger/users 
    - /opt/dlt/org/Org1/hyp-data/peer/:/var/hyperledger/production 
  working_dir: /opt/gopath/src/github.com/hyperledger/peer 
  command: peer node start 
  deploy: 
    replicas: 1 
    placement: 
      constraints: 
        - node.id == tuf7wb05mkl4ncw0spn8z2lss 
  restart: always 
  ports: 
    - 7051:7051 
    - 7053:7053 
  logging: 
    driver: "json-file" 
    options: 
      max-file: 5 
      max-size: 10m 
  networks: 
    - dev 
  depends_on: 
    - couchdb_peer1_org_io
    - ca_Org1
    - ord5_standardc_io 
    - ord4_standardc_io 
    - ord3_standardc_io 
    - ord2_standardc_io 
    - ord1_standardc_io 
```
