### ISSUE TITLE
"configtxlator compute_update" doesn't add new Org in read_set

### ISSUE THREAD

**Issue by hectordufau** [hyperledger/fabric#4399]
### Description

When adding a new org, "configtxlator compute_update" doesn't add new Org in read_set:

`configtxlator compute_update --channel_id "${CHANNEL}" --original original_config.pb --updated modified_config.pb --output config_update.pb`

### Steps to reproduce

* configtx.yaml content

```
Organizations:
 - Name: texasMSP
   ID: texasMSP
   MSPDir: 
     ./dockerfabricwizard/domains/teste.com/peerOrganizations/texas/msp
   AnchorPeers:
    - Host: peer1.texas.teste.com
      Port: 8051
   Policies:
     Readers:
       Type: Signature
       Rule: OR('texasMSP.admin', 'texasMSP.peer', 'texasMSP.client')
     Writers:
       Type: Signature
       Rule: OR('texasMSP.admin', 'texasMSP.client')
     Admins:
       Type: Signature
       Rule: OR('texasMSP.admin')
     Endorsement:
       Type: Signature
       Rule: OR('texasMSP.peer')
```

* commands executed

```
export FABRIC_CFG_PATH=${PWD}/dockerfabricwizard/domains/teste.com/config/build/

configtxgen -printOrg texasMSP > ${PWD}/dockerfabricwizard/domains/teste.com/config/texas.json

export CORE_PEER_TLS_ENABLED=true

export ORDERER_CA=${PWD}/dockerfabricwizard/domains/teste.com/ordererOrganizations/tlsca/tlsca.teste.com-cert.pem

export ORDERER_ADMIN_TLS_SIGN_CERT=${PWD}/dockerfabricwizard/domains/teste.com/ordererOrganizations/orderer/tls/server.crt

export ORDERER_ADMIN_TLS_PRIVATE_KEY=${PWD}/dockerfabricwizard/domains/teste.com/ordererOrganizations/orderer/tls/server.key

export CORE_PEER_LOCALMSPID="utahMSP"

export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/dockerfabricwizard/domains/teste.com/peerOrganizations/utah/tlsca/tlsca.utah.teste.com-cert.pem

export CORE_PEER_MSPCONFIGPATH=${PWD}/dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp

export CORE_PEER_ADDRESS=peer1.utah.teste.com:7051

export CHANNEL="teste"

peer channel fetch config config_block.pb -o orderer.teste.com:7050 --ordererTLSHostnameOverride orderer.teste.com -c $CHANNEL --tls --cafile "$ORDERER_CA"

configtxlator proto_decode --input config_block.pb --type common.Block --output ${PWD}/dockerfabricwizard/domains/teste.com/config/config_block.json

jq .data.data[0].payload.data.config ${PWD}/dockerfabricwizard/domains/teste.com/config/config_block.json > ${PWD}/dockerfabricwizard/domains/teste.com/config/config.json

jq -s '.[0] * {"channel_group":{"groups":{"Application":{"groups": {"texasMSP":.[1]}}}}}' ${PWD}/dockerfabricwizard/domains/teste.com/config/config.json ${PWD}/dockerfabricwizard/domains/teste.com/config/texas.json > ${PWD}/dockerfabricwizard/domains/teste.com/config/modified_config.json

configtxlator proto_encode --input ${PWD}/dockerfabricwizard/domains/teste.com/config/config.json --type common.Config --output ${PWD}/dockerfabricwizard/domains/teste.com/config/original_config.pb

configtxlator proto_encode --input ${PWD}/dockerfabricwizard/domains/teste.com/config/modified_config.json --type common.Config --output ${PWD}/dockerfabricwizard/domains/teste.com/config/modified_config.pb

configtxlator compute_update --channel_id "${CHANNEL}" --original ${PWD}/dockerfabricwizard/domains/teste.com/config/original_config.pb --updated ${PWD}/dockerfabricwizard/domains/teste.com/config/modified_config.pb --output ${PWD}/dockerfabricwizard/domains/teste.com/config/config_update.pb

configtxlator proto_decode --input ${PWD}/dockerfabricwizard/domains/teste.com/config/config_update.pb --type common.ConfigUpdate --output ${PWD}/dockerfabricwizard/domains/teste.com/config/config_update.json
```

* config_update.json result

![configupdateproblem](https://github.com/hyperledger/fabric/assets/12888215/a468dde8-037f-4995-bfe6-706438e28475)
