### ISSUE TITLE
CCAAS not support by 3.0.0-preview

### ISSUE THREAD

**Issue by bh4rtp2023** [hyperledger/fabric#4425]
### Description

When install chaincode, it reports an error:

```Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: platform builder failed: Failed to generate a Dockerfile: Unknown chaincodeType: CCAAS```

Release-2.5 is OK.

**Comment by satota2** [comment]
Hello @bh4rtp2023
I can confirm that CCaaS works fine in my local v3.0.0-preview environment and can not reproduce your problem. I tried [this instruction](https://github.com/hyperledger/fabric-samples/blob/main/test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md).

From your error message, it seems that the peer has not found the CaaS builder binary.
Check your peer's configuration file (core.yaml) to see if the following blocks are described:

```yaml
    externalBuilders:
       - name: ccaas_builder
         path: /opt/hyperledger/ccaas_builder
         propagateEnvironment:
           - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG
```
